### ISSUE TITLE
Dracula theme broken in Standard Notes > 3.9.15

### ISSUE THREAD

**Issue by ghost** [SlyBouhafs/sn-theme-dracula#13]
The note selector is always white since the last update. 

![image](https://user-images.githubusercontent.com/91443226/150751929-3a2063fc-8227-404e-ace1-f3e76e3fe687.png)

**Comment by ghost** [comment]
Any update on this?

**Comment by ghost** [comment]
I can confirm same issue in Desktop app and in the browser.

**Comment by sollymay** [comment]
this is very annoying as you can barely read what's underneath 👎. would love to see a fix soon

**Comment by SlyBouhafs** [comment]
Thanks for reporting! The Issue was fixed, please wait for JSdeliver cache to update.

**Comment by sollymay** [comment]
hey @SlyBouhafs seems like JSdeliver has not cached the update, so the issue persists as the instructions are still pointing at v0.16

**Comment by SlyBouhafs** [comment]
@sollymay Yeah, it looks like static files cached on the CDN do not get purged at all, can you try this link instead? Branches cache is purged every 12h.

`https://cdn.jsdelivr.net/gh/dracula/standard-notes@master/sn-theme-dracula.json`

I'll update the install instructions with this new link.

**Comment by sollymay** [comment]
this one works! thanks for the quick response
